spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:5434/mydatabase?serverTimezone=UTC
    hikari:
      username: test
      password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  docker:
    compose:
      skip:
        in-tests: true
      file: ./db-module/compose.yaml