server:
  port: 8189
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?serverTimezone=UTC
    hikari:
      username: test
      password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  docker:
    compose:
      skip:
        in-tests: false
      file: ./REST-module/compose.yaml